# Generated by Django 5.2.4 on 2025-08-27 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ambiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreAmbiente', models.CharField(max_length=100)),
                ('TipoAmbiente', models.CharField(max_length=100)),
                ('Observacion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'ambientes',
            },
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=100)),
                ('Tipo', models.CharField(max_length=100)),
                ('Observacion', models.CharField(max_length=255)),
                ('Foto', models.CharField(max_length=255)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbienteSena.ambiente')),
            ],
            options={
                'db_table': 'elemento',
            },
        ),
        migrations.CreateModel(
            name='Cuentadante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField(blank=True)),
                ('fechaasignacion', models.DateField(auto_now_add=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbienteSena.elemento')),
            ],
            options={
                'db_table': 'cuentadante',
            },
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreCompleto', models.CharField(max_length=255)),
                ('Area', models.CharField(max_length=255)),
                ('Celular', models.CharField(max_length=20)),
                ('Cedula', models.IntegerField(max_length=50)),
                ('elementos', models.ManyToManyField(related_name='instructores', through='AmbienteSena.Cuentadante', to='AmbienteSena.elemento')),
            ],
            options={
                'db_table': 'instructor',
            },
        ),
        migrations.AddField(
            model_name='cuentadante',
            name='instructor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbienteSena.instructor'),
        ),
        migrations.AlterUniqueTogether(
            name='cuentadante',
            unique_together={('instructor', 'elemento')},
        ),
    ]
