# Generated by Django 5.2.4 on 2025-08-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSena', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='Cedula',
            field=models.IntegerField(verbose_name=50),
        ),
    ]
