# Generated by Django 5.2.4 on 2025-09-12 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AmbienteSena', '0002_alter_instructor_cedula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacion', models.TextField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_salida', models.DateTimeField(blank=True, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbienteSena.ambiente')),
                ('instructor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='AmbienteSena.instructor')),
            ],
            options={
                'db_table': 'ingreso',
                'unique_together': {('instructor', 'ambiente')},
            },
        ),
    ]
